Document: msaview
Title: Debian msaview Manual
Author: <insert document author here>
Abstract: This manual describes what msaview is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/msaview/msaview.sgml.gz

Format: postscript
Files: /usr/share/doc/msaview/msaview.ps.gz

Format: text
Files: /usr/share/doc/msaview/msaview.text.gz

Format: HTML
Index: /usr/share/doc/msaview/html/index.html
Files: /usr/share/doc/msaview/html/*.html
